### ISSUE TITLE
PXE Full Host Registration resetting group settings

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#130]
Hello again

Following situation.

We start setting up a group in Fog management, set the options like boot image, efi settings, active directory settings and so on.

The we do a PXE boot and use the Full host registration so we can also set the hostname.
After we entered the hostname (because we want to use the predefined settings from the group we configured before, maybe the user who is setting up the host doesn't know which one to use) we don't pick an image, leave active directory blank and just pick the group.

Now when the host registers, it overwrites all the groups settings! 
So if we don't set AD, AD gets blanked in that **group**. if we don't set an image, the image is removed from the **group**. 
And so on. This means, it doesn't just register the host a member of the group but also changes/resets the whole group settings.

I might be wrong, but setting up a host should not discard any settings made for the group the host was assigned to. This would make the whole group thing useless because when I have to setup everything for each host I add to a group, I can also leave out the "add to group" step and save some time. 

Or am I wrong?

Regards

**Comment by mastacontrola** [comment]
You are wrong.

Group's don't store host relevant data.  The way they're displayed is based on all hosts in the group having the exact same content.  If one host in the group has different setting, the value it is different from will be blanked out by the group.  If you check another host who had the settings applied by the group prior, it should still contain the same data.

**Comment by mastacontrola** [comment]
For example:

AD.

If you have 50 hosts in the group (including the freshly registered one) and one (or more) of those hosts don't have matching AD data, the ad data field will be blank, but all the other hosts should still have their original matching information.  Hopefully that makes sense.

**Comment by mastacontrola** [comment]
If this helps answer the question, please just comment and close, I'm kind of stuck to phone at the moment so while I can close it, I figure I'll wait for your input.

**Comment by Nightreaver** [comment]
This means.. it's like you have a text document with two different fonts, whenever I select text with only has one font, I can still see the font name. When I select text with more than one font, the fields gets blanked until I set a new font for the whole text?

But then I don't really get the reason for a group then. I was thinking of  layered structure, global first, then group, then host. So I can override each setting separately. This makes the group to just a "collection" of hosts so I set host specific stuff faster, but still on a "per host" basis.

**Comment by mastacontrola** [comment]
That's is absolutely the case.

Groups aren't a definitive template for hosts that associated, because hosts can belong to Multiple groups.  Group's in FOG's sense are simply a quick means to set all hosts with the same information.  Simply adding a host to a group does not make the group's other settings apply automatically to the host.

There is a "way" to do this but it's not a "thing" I'm going to implement.  We have plans to add "persistent" group settings for the next workup of FOG though.

Look for "Persistent Group settings" on forums.fogproject.org, and look specifically for the user george1421.  He created a mechanism that will automatically apply the groups settings to the newly added host(s).  The concept is create an SQL Trigger.  That trigger looks for a "dummy" hostname that matches the group's name of which you apply your wanted group settings to.  This "dummy" host essential is your "group" template.

**Comment by mastacontrola** [comment]
https://forums.fogproject.org/topic/6902/fog-1-3-persistent-groups/12#

**Comment by Nightreaver** [comment]
I see, thanks for clarifying.
