### ISSUE TITLE
Error during installation (1.3.0-RC-21 to 1.3.0)

### ISSUE THREAD

**Issue by alexandre-lg** [FOGProject/fogproject#150]
Hello,

Error with awk during the installation process on Debian 8.6:
```
 * Removing vhost file.........................................OK
awk: line 1: syntax error at or near ,
 * Setting up Apache and PHP files.............................OK
```
This is a non-blocking error, but is it inconsequential?

Thanks for your incredible work!

**Comment by mastacontrola** [comment]
Are you having problems after installing?

**Comment by mastacontrola** [comment]
I'm assuming this is because gawk is not installed ( as is often the case ).  This, I'm guessing, was an update?

Line 1559 of the lib/commons/functions.sh file ( I believe) is where you're seeing the error present. I don't think it should cause issues, unless Debian has switched mysql to require sudo if the root password is blank.

**Comment by mastacontrola** [comment]
I just wanted to add, I've updated the installer to no longer use the "awk" form to get the information it's looking for.  Please update and let me know if you're still seeing the error.

**Comment by alexandre-lg** [comment]
Hello,

Sorry for my absence. What version should I install to test?
