### ISSUE TITLE
Database update fails on 1.3.4-RC-2

### ISSUE THREAD

**Issue by davemc50** [FOGProject/fogproject#155]
1064 You have an error in your SQL syntax;

ALTER TABLE `fog`.`_globalSettings` ADD UNIQUE INDEX INDEX (`settingKey`)

should read

ALTER TABLE `fog`.`_globalSettings` ADD UNIQUE INDEX (`settingKey`)

**Comment by mastacontrola** [comment]
Fixed in latest dev-branch (still RC-2).

Please repull and all should be well.

**Comment by mastacontrola** [comment]
You may also need to set your schemaversion to one behind what it was working from when the error was thrown.

For example, I dropped my database and tested the issue.

It failed for me on schema version 130.

To ensure all was well, I had to reset the db schema version to 131.  You would also need to remove the _globalSettings table that was created.  I don't have a good enough means to add a way to correct the left over table.

**Comment by davemc50** [comment]
Mehh, it flakes on column already existing.

I put the schema back to 130 as you suggest

update schemaVersion set vValue=130 where vID=1;

But the update dies

Column already exists: 1060 Duplicate column name 'ipxeVersion'

ALTER TABLE `ipxeTable` ADD COLUMN `ipxeVersion` LONGTEXT NOT NULL

to make it more resiliant could be 

IF NOT EXISTS( SELECT NULL
            FROM INFORMATION_SCHEMA.COLUMNS
           WHERE table_name = 'tablename'
             AND table_schema = 'db_name'
             AND column_name = 'columnname')  THEN

  ALTER TABLE `TableName` ADD `ColumnName` int(1) NOT NULL default '0';

END IF;

**Comment by mastacontrola** [comment]
I have a column checker/getter, but there's a LOT of schema code. I didn't suggest you go back to 130 simply because my error was due to a completely fresh database creation, yours was likely far forward from that.

You should have a backup DB in /home/fogDBbackups from before the first install.

Would you mind replacing your current DB with that file, and rerun the update with the fixed INDEX INDEX issue?  It shouldn't have any more problems.

The reasoning I make this request is because I don't know where in the schema it's doing "things".  These things have the potential to add duplicate entries in the database, in particular to the global settings table.  This makes the bootmenu act a bit weird as more data is passed in than what's being requested.
