### ISSUE TITLE
Add hot keys to IPXE menu

### ISSUE THREAD

**Issue by dfear** [FOGProject/fogproject#159]
Hotkeys on the IPXE menu would be very useful.

**Comment by mastacontrola** [comment]
I don't understand what you mean?

This isn't something FOG can do, this is something you may want to request from iPXE.

**Comment by dfear** [comment]
Of course it is something that FOG can do.

All that FOG does is generate an ipxe menu using php.

**Comment by mastacontrola** [comment]
What do you mean though?

If you're talking about mapping keys to get to different menu's and you're saying it can be added to the menu, then add it.  You can edit the menus now, so adding the relevant commands is simple.

**Comment by mastacontrola** [comment]
http://ipxe.org/cmd/item

I'm assuming you're referring to the --key element on the items?

**Comment by Sgmaniac1255** [comment]
if i understand correctly i think what @dfear  is asking for is key shortcuts for menu options in the iPXE menu

ie
(1) boot ide
(2) reg host
(3) quit reg host
ect...

so when the menu populates you hit the 1, 2, or 3 keys respectively for each menu option instead of arrow-ing to them and striking enter

**Comment by mastacontrola** [comment]
I think I understand that now, and that's why I brought up the item above. I don't have to do the key sequences.  You guys can modify them how you see fit.

**Comment by mastacontrola** [comment]
https://forums.fogproject.org/topic/9836/add-hot-keys-to-ipxe-menu
