### ISSUE TITLE
Disk wont resize when using nvme

### ISSUE THREAD

**Issue by flaviodr** [FOGProject/fogproject#208]
If the image is created using nvme, the recovery won't resize to use the full disk when the recovery disk is bigger than the original image.

The process was done using FOG 1.4.4 and Surface 4Pro:

1. Created an image of the Surface4Pro - 128GB
2. Restore the image to the Surface4Pro - 256GB (Disk will not resize and remain as only 128GB)

Thank you,

**Comment by Sebastian-Roth** [comment]
From what you say it sounds as if resize is working properly on other disks, right? Just wanna make sure this is not a general issue with resizing in your environment.

We have fixed a couple of things in the working branch which might address the issue you see:
https://github.com/FOGProject/fogproject/commits/working/src/buildroot/package/fog/scripts/usr/share/fog/lib/procsfdisk.awk

Mind upgrading your FOG server to the latest working branch commit to see if this is fixed for you then.

**Comment by FlavioDR** [comment]
I installed the working branch but I got the same problem.

I was able to solve this problem following the steps below:

Cloned the Surface4Pro 128GB using Clonezilla Live
Restored the Clonezilla Surface4Pro 128GB  image using Hyper-V machine
On Fog, I captured the image of the Hyper-V machine
Restored the Surface image from FOG Server on the SurfacePro 4 256GB
*Using this method the disk was resized from 128Gb to 256GB.

Conclusion:
The problem seems to be creating the image using nvme disk.

**Comment by Sebastian-Roth** [comment]
Would be great if we can figure this out together and get it fixed in FOG. Please create a new image definition in FOG web UI so you don't mess with the other stuff you created. Configure your Surface4Pro 128GB master to use that new image and schedule a **debug capture task** to upload  a fresh image. Boot up the client, hit ENTER twice to get to the shell and run `blkid` and `gdisk-l /dev/nvme0n1`. Take a picture of the output and then start the upload - command `fog`. Step through the process. After it's done please get the files `d1.partitions`, `d1.minimum.partitions` and `d1.fixed_size_partitions` and post contents of all those here.

I get the impression that this has nothing to do with NVMe disk but we'll see.

**Comment by mastacontrola** [comment]
I know many people using NVME disks and they're not running into an issue so I have to side with you @Sebastian-Roth

**Comment by FlavioDR** [comment]
Please give me a few more days to take this test.
Thanks,

**Comment by FlavioDR** [comment]
My test:

[](url)


![img_4564](https://user-images.githubusercontent.com/32853396/32673419-2836bb28-c61d-11e7-92cf-6519b46da585.JPG)
![img_4561](https://user-images.githubusercontent.com/32853396/32673420-2845648e-c61d-11e7-9b28-18a5a679b20f.JPG)
![img_4560](https://user-images.githubusercontent.com/32853396/32673421-284f4850-c61d-11e7-9dbb-3f45e29dc86a.JPG)
![img_4559](https://user-images.githubusercontent.com/32853396/32673422-285b84a8-c61d-11e7-8283-47fe46c78b80.JPG)

[d1.partitions.txt](https://github.com/FOGProject/fogproject/files/1462370/d1.partitions.txt)
[d1.minimum.partitions.txt](https://github.com/FOGProject/fogproject/files/1462371/d1.minimum.partitions.txt)
[d1.fixed_size_partitions.txt](https://github.com/FOGProject/fogproject/files/1462372/d1.fixed_size_partitions.txt)

**Comment by Sebastian-Roth** [comment]
Ok, in your case several issues seem to play a role but from what I see it's definitely **not** the NVMe disk!
* The `d1.fixed_size_partitions` states `:1:2:3` which means FOG detected all those partitions as being important not to resize!
   * For partition 1 (EFI loader, VFAT) thats ok.
   * Your partition 2 is an important one as it contains Windows boot loader files and should not be resized by FOG. Though I am a bit puzzled as it does **not** show `TYPE=` which means that Linux cannot see there is a (NTFS) filesystem on that partition.
   * Partition 3 is your main Windows partition - Now here comes the interesting question why FOG marks this partition to be fixed. It shouldn't! This is the main question in this riddle and I can't answer this one based on the information we have so far.
   * And partition 4 is a recovery partition which from my point of view should be marked as fixed but it's not. That's because the partition label is not set to "RECOVERY". 
* Another big question is why do we only see three partitions in the windows disk management picture. Is that after deploying your image to a machine or before capturing from it? From the disk size to me it looks as it is after a deploy. But that doesn't make sense. FOG doesn't loose a partition right in the middle of the disk. Partition 2 is missing and seems like the main Windows partition took over that part - which is possible to do but not something FOG is doing. Please tell us where those pictures were taken from.
* To better understand what's going wrong I need you to ask to do the following two things:
   * First schedule a **debug** upload task for your master machine, boot it up and when you get to the shell try mounting the third partition by hand: `mount.ntfs-3g /dev/nvme0n1p3 /mnt; ls -al /mnt; umount /mnt` and take a picture of the screen to post here. Then shut down that machine and cancel the task in the FOG web UI
   * Second schedule a **debug** download/delpoy task for one of your other machines. Start the imaging via `fog` command and step through it. Take pictures of all the things you see on screen except the pre banner stuff (**not** one picture for every step but one for each screen will do). Even seeing one picture of each blue partclone window might be handy as we see the filesystem type there too.

**Comment by FlavioDR** [comment]
1. Actually, FOG cloned all the 4 partitions. The "Reserved" partition is hidden on the Windows disk management.  I attached an image of both Surfaces, 128GB and 256GB,  with diskpart opened that show all the 4 partitions. 

2. The windows disk management picture was taken after the deployment to show the problem that the disk was not resized right. However, the "Reserved" partition is hidden by Windows.

3. I would like to remember that if a deploy an image on the Surface 4 Pro using the image of the Surface Pro 3, the hard drive of the Surface 4 Pro is resized normally. It seems that problem is when the image is created.


I believe I attached all the images that you asked for. Let me know please if I missed something. Thanks,

[images.zip](https://github.com/FOGProject/fogproject/files/1472732/images.zip)

**Comment by Sebastian-Roth** [comment]
Ok, thanks for the information and pictures! First I get to your comments:
1. Still learning something new every day. Didn't know about [Microsoft Reserved Partition (MSR)](https://en.wikipedia.org/wiki/Microsoft_Reserved_Partition) actually being hidden from the disk management tool. Makes a lot more sense now.
2. Yeah, got that.
3. Yes the problem as I see it is that FOG does not recognize your main Windows partition (number 3) as being resizeable when it captures the image. So you end up with `:1:2:3` in the d1.fixed_size_partitions file and with that FOG won't resize your main partition on deploy.

So what you can do for now is edit that file mentioned and make it read `1:2:4` (or `:1:2:4`, doesn't matter). I will be digging through the code again to see if I can figure out why on earth it does recognize your third partition as fixed - shouldn't do!

From the pictures we see that the partitions seem to be recognized as they should be by partclone. d1p1=FAT32, d1p2=RAW, d1p3=NTFS, d1p4=NTFS

About the UUID error in one of your pictures. Can you post the contents of `d1.original.uuids` as well. Maybe this will shed a light on what's causing this.

**Comment by Sebastian-Roth** [comment]
Closing this issue as we have not had any comment in a long time.
