### ISSUE TITLE
internationalized configuration

### ISSUE THREAD

**Issue by huannanchunli** [FOGProject/fogproject#230]
Modify the internationalized configuration, but not completely internationalized, such as the menu on the left of the user，version 14.4 does not have this problem
![image](https://user-images.githubusercontent.com/8775486/35855802-26fa5c78-0b6f-11e8-9123-6219d0a747a8.png)

**Comment by mastacontrola** [comment]
While I understand the problem, I don't know that there's much that I can actually do to fix it.  This is because, or so it appears, the gettext usability in PHP is not translating through sprintf/printf type formatting. (For example:)
```
//List all is provided by variable in text.php.
// This appears as:
$foglang['ListAll'] = _('List All %s');

// The Translation is present in the relevant .po files as:
// Looks like chinese to me right now:                                                                       
 msgid "List All %s"                                                                                   
 msgstr "列表中的所有%s"

// The output occurs in fogpage.class.php
sprintf(self::$foglang['ListAll'], _($this->childClass));
// Child class is a reference to the current node you're located on. (In your pic "Users").
// self::$foglang is a variable for the classes to access the $foglang variables more dynamically.
```

As you can see, the Translation is indeed there, but for whatever reason it's not translating format strings, and I don't know why currently. I suspect maybe a problem with newer versions of PHP? (I'm guessing you're running PHP 7.0)
