### ISSUE TITLE
Update to PHP 7.2, remove mcrypt

### ISSUE THREAD

**Issue by abulhol** [FOGProject/fogproject#264]
The Fog installer still requires PHP7.1 due to mcrypt, but when I look at the code, mcrypt is only used in Test.php and nowhere else. See also https://github.com/FOGProject/fogproject/issues/226
Can you please remove it and update the installation config? 
PHP 7.2 is now the default on Ubuntu 18.

**Comment by Quazz** [comment]
This is an issue if you've been updating FOG from older versions.

FOG hasn't used mcrypt for a while (since 1.4 or so iirc), but if you were using FOG at the time, the mcrypt package will exist in the packages collection in /opt/fog/.fogsettings

Removing it from that line (or the line itself) should correct the issue

**Comment by Nono-m0le** [comment]
Actually, I would also like this to happen, if possible. Ubuntu 18.04.1 comes already with php 7.2 (no need to add the ondrej repo).
I've noticed that on the latest version (fresh install, not upgrade) of FOG 1.5.4, there is, on the /lib/ubuntu/config.sh those lines : 

```
54                 dots "Resetting our variables to specify php version 7.1"
55                 php_ver="7.1"
[...]
62                 packages="apache2 build-essential cpp curl g++ gawk gcc genisoimage gzip htmldoc isc-dhcp-server isolinux lftp libapache2-mod-fastcgi libapache2-mod-php${php_ver} libc6 $libcurl liblzma-dev m4 mysql-client mysql-server net-tools nfs-kernel-server openssh-server $phpfpm php-gettext php${php_ver} p    hp${php_ver}-cli php${php_ver}-curl php${php_ver}-gd php${php_ver}-json $phpldap php${php_ver}-mcrypt php${php_ver}-mysql php${php_ver}-mysqlnd sysv-rc-conf tar tftpd-hpa tftp-hpa vsftpd wget xinetd zlib1g"
```

Would that be sufficient/okay/safe to change the line 55 by : 
`php_ver="7.2"`
and remove the `php${php_ver}-mcrypt` from the line 62 ?

I know it's not a proper solution, because I would have to remove the ondrej installation steps, but on the meantime ?

So far, I've tried to use PHP 7.2 (by removing manually the ondrej repo) and it's currently running without issue.

**Comment by Sebastian-Roth** [comment]
@abulhol Should be fixed in working branch now. See merged code changes above. Hope I got it all right so that existing Ubuntu 18.04 installations will also remove the ondrej repo and install PHP 7.2 when running the installer again.

**Comment by abulhol** [comment]
Nice, thanks! I will test it and let you know in case of problems.

**Comment by Nono-m0le** [comment]
just wanted to let you know that I had to try out and it works like a charm ! (the API is still not working out of the box, but following instruction from #263 seems to be okay for the time being.

PS: @Sebastian-Roth I notice this during the installation, not sure if it's still needed or not ?
`* Adding needed repository....................................OK`
