### ISSUE TITLE
Lots of DNS queries on imaging tasks

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#270]
A user mentioned to me seeing a huge amount of DNS queries (image names) going on when sending an image to a client. Need to look into that and find out why we do this.

**Comment by mastacontrola** [comment]
I know during imaging, DNS requests from the client to the server may be being performed as every 3 seconds or so status reporting is occurring. Maybe this is playing into it a bit? Particularly if the storage node being pulled from is using a hostname rather than a DNS?

One thing to look for in the code might be `resolveHostname`

**Comment by Sebastian-Roth** [comment]
While working on a similar topic that was brought up in the forums ([ref](https://forums.fogproject.org/topic/13530/fog-generates-lots-of-dns-queries)) I have tested capture, deploy, multicast and can't see any situation where FOG would query "image names" via DNS. As well couldn't find anything in the code.

As this hasn't been touched in over six months I am just going to close it now as "nothing to fix, works as intended".
