### ISSUE TITLE
Ask user if we should delete an old snapin binary

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#273]
jflippen said [in the forums](https://forums.fogproject.org/post/118588):
> If I upload a different filename for a snapin, the old file associated with the snapin does not get removed from either the master or the storage nodes. This can be an issue for MSI files that update their file name with each release (e.g. Java updates). I have found sometimes I may accidentally have the syntax wrong as well and have to re-upload a file. However, this leaves me manually going into the snapins folder to cleanup old files. Not a deal breaker, but I felt this is something that should be noted.

Idea to resolve this: The best way I find would be to ask the user if we should delete the old binary when editing a snapin takes place and a different filename is used. This way people can decide if they want to keep the old binary on the server (might use it later) or not.

**Comment by Sebastian-Roth** [comment]
Feature, needs to wait.

**Comment by mastacontrola** [comment]
I feel I need to comment.

I have incorporated this "feature" into working-1.6. That said it does not ask the user if you'd like to delete it. The reasoning, at the point that the file update can be checked, the form has already been posted. While I could incorporate a secondary modal that pops up asking you to confirm, the flow would seem to be .... lacking.

I'm of the opinion this should be done anyway.

Effectively, anytime you update the snapin with a new file, you should remove the original file and put the new file in place. Regardless of if it's the same name, or a totally new name.

Files names are not a unique item so it's technically possible for 2 snapins to use the same file. In this case I've implemented some logic that should help prevent accidental deletions of this.
* Just to try to visualize: snapina uses file abc, snapinb is input and you decide to set it with file abc.
  * You learn snapina has a new file you want to use called def. You want to update it, so you do. The file abc will not be deleted because snapinb is still referencing it.
  
 Hopefully this addresses the problems and pieces you were hoping for. Granted it doesn't ask if it should delete the original file or not, but I think that's okay. Functionally speaking you are telling it to not use that file any longer.
