### ISSUE TITLE
PHP warnings that might cause issues in later versions

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fogproject#285]
Hi @mastacontrola, by accident I came across this in the php-fpm.log on a recent CentOS install that is now using PHP 7.2:
```
[25-Jan-2019 18:43:39 UTC] PHP Warning:  Use of undefined constant TFTP_PXE_CONFIG_DIR - assumed 'TFTP_PXE_CONFIG_DIR' (this will throw an Error in a future version of PHP) in /var/www/html/fog/commons/schema.php on line 380
[25-Jan-2019 18:43:39 UTC] PHP Warning:  Use of undefined constant PXE_IMAGE_DNSADDRESS - assumed 'PXE_IMAGE_DNSADDRESS' (this will throw an Error in a future version of PHP) in /var/www/html/fog/commons/schema.php on line 414
[25-Jan-2019 18:43:39 UTC] PHP Warning:  Use of undefined constant USER_VALIDPASSCHARS - assumed 'USER_VALIDPASSCHARS' (this will throw an Error in a future version of PHP) in /var/www/html/fog/commons/schema.php on line 484
[25-Jan-2019 18:43:39 UTC] PHP Warning:  Use of undefined constant FOG_THEME - assumed 'FOG_THEME' (this will throw an Error in a future version of PHP) in /var/www/html/fog/commons/schema.php on line 513
[25-Jan-2019 18:43:39 UTC] PHP Warning:  Use of undefined constant FOG_DONATE_MINING - assumed 'FOG_DONATE_MINING' (this will throw an Error in a future version of PHP) in /var/www/html/fog/commons/schema.php on line 1717
```

At first I thought we should never be changing old schema definitions but add a new one to remove those settings from the DB in a later schema version. But then I figured that we'd run into the same warnings (later errors) if we don't add those defined to `config.class.php` as well. Thinking a bit about it I don't see why we should go the long router?! Better remove those defines from the schema altogether. What do you think?

**Comment by mastacontrola** [comment]
We can remove the elements that used these lines in schema and just set them to blank. This is because the older versions used this from the config.class.php (but we no longer need this.  So we can safely replace these lines with blank information. (Or if you really want just place a false place holder.)

Deleted in later schema versions (and version number that removed in incase you're worried.)

TFTP_PXE_CONFIG_DIR -> FOG_TFTP_PXE_CONFIG_DIR removed Schema V. 98
PXE_IMAGE_DNSADDRESS -> FOG_PXE_IMAGE_DNSADDRESS removed Schema V. 220
USER_VALIDPASSCHARS -> FOG_USER_VALIDPASSCHARS not removed, however in 1.6 we're using a REGEX pattern, Default regex is: `(?=.*){4,}`. I think you can safely leave it as `abcdefghijklmnoprstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=_+!@#$%^&*(){}|[]\:";'<>?,./` this was just a string containing all the viable characters for passwords you may have wanted.
FOG_THEME set to string purely `default/fog.css`
FOG_DONATE_MINING -> I don't remember when I removed it, but a blank value or set to `0` will be fine.

**Comment by Sebastian-Roth** [comment]
@mastacontrola Thanks for your answer! Sure thing we could just set those in the config.class.php to blank or zero values. But I was more hoping to entirely remove some or even all of those from the code just to do a bit of housekeeping. What use case do we have that would count for leaving them in the schema and set to empty/zero values in config.class.php. From my point of view this would only play a role if people have FOG with a lower schema version (e.g. 200) installed and upgrade to the latest. In that case the schema delete won't kick in and would leave them with a phantom entry in globalSettings. Not a big deal in my eyes. I don't think anything else can go wrong?!?

If we entirely remove the stuff from schema.php now it saves us from creating and deleting useless settings on initial schema update and we'd have less useless settings in config.class.php. On the other hand we kind of loose the information that those settings have existed at some point. But if we mention those in the git commit message we should be able figure it out again very quickly in case we need to.

What do you think?

About `USER_VALIDPASSCHARS` - this was "silently" removed from config.class.php in 2016 (38d2cf26) and seems like it was never really used in the DB anyway. I tend to remove that just as well. Not used, not needed.

`FOG_THEME` seems still useful to me. Would leave that as is and add set to `default/fog.css` in config.class.php

The other three (`TFTP_PXE_CONFIG_DIR`, `PXE_IMAGE_DNSADDRESS` and `FOG_DONATE_MINING`) I vote for entire removal as mentioned above.

**Comment by Sebastian-Roth** [comment]
@mastacontrola Pushed 4dd68f6 - mind adding to `working-1.6` as well and then closing the issue?

**Comment by mastacontrola** [comment]
Added in `working-1.6` by dbab966
