### ISSUE TITLE
Installation should not require CWD to be in the bin/ directory

### ISSUE THREAD

**Issue by AccidentallyTheCable** [FOGProject/fogproject#286]
Installation script does a source of ../lib/functions.sh. This should be made into a properly relative path such as `$(dirname $(dirname $0))/lib/functions.sh`

Trying to install while not in bin/ directory fails.

**Comment by Sebastian-Roth** [comment]
We actually ask people to change to the `bin/` directory because the log files will be written to that directory as well. As I said in the other issue the installer might need a major re-write at some point and that is definitely something I'd consider doing a different way. But nevertheless you are right that not checking this properly is not the right way!

Should be fixed in 7f31db1
