### ISSUE TITLE
Fog Schema does not take customized image location at install time.

### ISSUE THREAD

**Issue by AccidentallyTheCable** [FOGProject/fogproject#290]
As a result of our environment and needs, I needed to have the images location in another place, so that it could be on a separate disk, which holds other information.

During the install, specifying storageLocation works for most everything, EXCEPT the schema, and potentially one other place.

Here: https://github.com/FOGProject/fogproject/blob/master/packages/web/commons/schema.php#L845

and

(Possibly?) Here: https://github.com/FOGProject/fogproject/blob/master/packages/web/lib/hooks/boottask.hook.php#L83

**Comment by Sebastian-Roth** [comment]
@AccidentallyTheCable said:
> As a result of our environment and needs, I needed to have the images location in another place, so that it could be on a separate disk, which holds other information.

I have not reviewed the parts of the code you linked yet. As a quick workaround you should always be able to just **mount** whatever disk you have to `/images`. This should work in pretty much any situation.

**Comment by mastacontrola** [comment]
I'm applying a test patch to `working-1.6`

Essentially, in the schema location that `/images/` is defined, I'm calling:

```
shell_exec('source /opt/fog/.fogsettings; echo $storageLocation');
```

Note the single quotes are important as otherwise we have to escape the `$` symbol.

@Sebastian-Roth, do you think this would be a better approach? Or even do you have a better idea?  I didn't think about it so long ago, as typically we update the `/images/` during the checking the setting/configuration element of the storage node during installs. (Or so I thought we did.)

**Comment by mastacontrola** [comment]
I've modified and tested a simple fix. It appears to be working. In the midst of doing this work, I also found another installer issue of which I've addressed.

Please see here: c9630ce

I know this is not on the dev-branch, but the information is still viable. Hopefully this will give some insight and work as intended.

**Comment by Sebastian-Roth** [comment]
@mastacontrola Thanks for your proposed fix. I just added it to `dev-branch` as well.

@AccidentallyTheCable On a fresh install AFAIK you'd still need to set the variable before running the installer:
```
export storageLocation=/path/to/images
/path/to/fogproject/bin/installfog.sh ...
```
