### ISSUE TITLE
NFS(TCP) with "secured" switches.

### ISSUE THREAD

**Issue by igorfk** [FOGProject/fogproject#325]
More like a comment than an issue: some switches by default could enable by default a feature to mitigate DDoS attacks blocking TCP SYN below ports 1024, which in turn affects NFS on TCP.

I cannot find this observation elsewhere here in the project so fell free to remove it.

**Comment by Sebastian-Roth** [comment]
@igorfk Can you please explain in more detail what you mean. I don't see how this relates to anything in the FOG project world. Well, we do use NFS but that's about all I can relate.

**Comment by igorfk** [comment]
@Sebastian-Roth and all, sorry to not elaborate my comment.
Since NFS via TCP is used to transfer images and other files, relying on other services to redirect clients to proper port numbers, mount the filesystem etc the transfers will not function as expected if those services cannot communicate with their respective ports (portmap at 111, mountd at 836 etc) somehow blocked. These days is quite common to find switches blocking a range (ports below 1024), that will block those ports automatically, without manual intervention, if any suspicious traffic occurs to protect from SYN attacks.

**Comment by Sebastian-Roth** [comment]
@igorfk Thanks for clarifying! Definitely helpful. I think we even have some requests in the forums that could possibly be related to this.

We have thought about moving away from NFS at some stage. But this is a major change in FOG and does take time and effort. So it's not something coming any time soon. What I am wondering is, do those switches block any ports below 1024 if they see "suspicious traffic" (what exactly could that be? x connects within y minutes?)? What about HTTP/HTTPS and TFTP which is heavily used by clients that PXE boot and load the boot menu? What about SSH that we have discussed to use instead of NFS?!

**Comment by Sebastian-Roth** [comment]
Closing this as I don't think there will be more discussion on this. Feel free to re-open and post again if needed.
