### ISSUE TITLE
Error \deprecated php code during install of latest v.1.3.x 

### ISSUE THREAD

**Issue by espene** [FOGProject/fogproject#37]
Downloading kernels and inits...OK
  * Downloading New FOG Client file...PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
Deprecated: Directive 'register_long_arrays' is deprecated in PHP 5.3 and greater in Unknown on line 0
Deprecated: Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater in Unknown on line 0
Failed

I suppose a minor fix, but I havent really had time to check out the framework enough to supply a fix -at the moment- , so if someone feels fast and handy! if not i will pop back with a solution later on.

**Comment by mastacontrola** [comment]
Are you using Oracle as the database manager?  I ask this because magic_quotes_gpc only appears in the Oracle.class.php file.  The register_long_arrays function isn't even in use on any files in the FOG GUI Syste.  The module already loaded is a problem specific to Debian/Ubuntu as their module loading is done through:

/etc/php5/apache2 and /etc/php5/cli.  There's a folder along the lines of: /etc/php5/mods-available which is a symbolic link inside the /etc/php5/{apache2,cli}/mods folder.  As the apache service restarts, it loads the files located in these folders.  As an instance is loaded, and the other directory starts loading, we see the module already loaded issue.

**Comment by mastacontrola** [comment]
As nothing has been returned, I'm closing this report.
