### ISSUE TITLE
Impossible install on Ubuntu 18.04

### ISSUE THREAD

**Issue by CpServiceSpb** [FOGProject/fogproject#383]
On Ubuntu 18.04 with renamed ethernet interfaces from standard (ethX) to other (lanX) and address space differing from 192.168.0.0 (statically assigned) the following error during installation is appeared:

```
sed: -e expression #1, char 0: no previous regular expression
ERROR: Not able to find a network interface that is up on your system.
```

Fog 1.5.8 was downloaded by link [fog 1.5.8](https://github.com/FOGProject/fogproject/archive/1.5.8.tar.gz)

The same error is for 1.5.7 version.

Lan interfaces is statically set up, wan is also presented.
Both is up during installation.

**Comment by George1422** [comment]
I would recommend that you use the git method to install FOG and not via the tarball. And actually using the git method switch to the dev branch, the issue with ubuntu has been address in the dev branch of 1.5.8 (pre release of FOG 1.5.9).

**Comment by Sebastian-Roth** [comment]
@CpServiceSpb As requested in the forums, please run `ip a s` as root and post the full output here.

**Comment by CpServiceSpb** [comment]
Here is:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: wan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:XX:XX:XX:XX:3f brd ff:ff:ff:ff:ff:ff
    inet 10.XX.XX.XX/21 brd 10.XX.XX.255 scope global wan0
       valid_lft forever preferred_lft forever
3: lan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:XX:XX:XX:XX:3e brd ff:ff:ff:ff:ff:ff
    inet 10.10.0.254/24 brd 10.10.0.255 scope global lan0
       valid_lft forever preferred_lft forever
4: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1400 qdisc fq_codel state UNKNOWN group default qlen 3
    link/ppp
    inet 11.22.33.44 peer 11.22.33.1/32 scope global ppp0
       valid_lft forever preferred_lft forever
wan - is physical interface connected to an ISP network,
ppp0 - is vpn tunnel to its BRAS, 11.22.33.44 - my external white IP (of course it' s masked) .

**Comment by Sebastian-Roth** [comment]
@CpServiceSpb I need you to run another command and post output here: `ip -4 route show`

**Comment by CpServiceSpb** [comment]
Here is output for ip -4 route show:
default dev ppp0 scope link
10.10.0.0/24 dev lan0 proto kernel scope link src 10.10.0.XX
10.38.XX.0/21 <http://10.38.152.0/21> dev wan0 proto kernel scope link src
10.38.XX.16
XX.XX.254.1 via 10.38.XX.1 dev wan0



пн, 20 апр. 2020 г. в 08:04, Sebastian-Roth <notifications@github.com>:

**Comment by Sebastian-Roth** [comment]
@CpServiceSpb Sorry for the delay. Your routing/VPN setup is kinda special, not something we have come across ever before. I just pushed a fix to the `dev-branch` and you should be able to install FOG using the following download link: https://github.com/FOGProject/fogproject/archive/dev-branch.tar.gz

**Comment by CpServiceSpb** [comment]
By the way, is FOG installation internet connection dependable ?
Does it mean that I can not install FOG with Internet connection ?

And, regarding functioning, I have fully installed and working iPXE (git
version about 1 week ago) and atftpd version 0.7.
Will I be able to get working FOG with these components ?



вс, 26 апр. 2020 г. в 20:04, Sebastian-Roth <notifications@github.com>:

**Comment by CpServiceSpb** [comment]
And I forgot to mention that as Dhcp I have fully functioning Freradius
server with 66 and 67 option set up, as for 66 option is lan IP of the
server as for 67 option is undionly.kpxe.
All was installed but the following error was got: " * Starting and
checking status of web services................Failed!"

вт, 28 апр. 2020 г. в 22:47, CpServiceSPb . <cpservicespb@gmail.com>:

**Comment by CpServiceSpb** [comment]
Details of the error:
Apr 28 22:59:26 gate apachectl[28690]: [Tue Apr 28 22:59:26.896144 2020]
[core:trace3] [pid 28694:tid 139656855452608] core.c(3355): Setting
LogLevel for all modules to trace7
Apr 28 22:59:26 gate apachectl[28690]: AH00318: WARNING: MaxRequestWorkers
of 150 would require 6 servers and would exceed ServerLimit of 1,
decreasing to 25. To increase, please see the ServerLimit directive.

As for mpm model I use worker and need to be set up ServerLimit to 1 for
some other soft.

вт, 28 апр. 2020 г. в 23:02, CpServiceSPb . <cpservicespb@gmail.com>:

**Comment by CpServiceSpb** [comment]
Finnaly I am very disappointed that FOG removed by itself without warnings
and asking Freeradius (which is as Dhcp as well) and atftpd.

It is unacceptable, taking into account that I chose that FOG wouldn' t act
as Dhcp.

вт, 28 апр. 2020 г. в 23:14, CpServiceSPb . <cpservicespb@gmail.com>:

**Comment by CpServiceSpb** [comment]
And during FOG installation some other soft was removed, for example
Kannel, Freeradius and other soft using libpcre libpcre3 8.41 version,
reduce it to 8.39 also disset up my Php settings.
I had to re-set up some components and wasted a lot of time.

So, I would like that you add options to work together with atftpd as
another choise and other Dhcp server as another option.
Or make some instruction for advanced users.
Also as Php is incompatible with mpm-worker I installed php-frm.
I can provide atftpd conf files and some advices as well as Freeradius.



вт, 28 апр. 2020 г. в 23:26, CpServiceSPb . <cpservicespb@gmail.com>:

**Comment by CpServiceSpb** [comment]
Also I use Php from Ondřej Surý repository.

ср, 29 апр. 2020 г. в 01:16, CpServiceSPb . <cpservicespb@gmail.com>:

**Comment by Sebastian-Roth** [comment]
@CpServiceSpb There is no point in being disappointed about what FOG did as it's stated as a warning when you run the installer:
```
######################################################################
#     FOG now has everything it needs for this setup, but please     #
#   understand that this script will overwrite any setting you may   #
#   have setup for services like DHCP, apache, pxe, tftp, and NFS.   #
######################################################################
# It is not recommended that you install this on a production system #
#        as this script modifies many of your system settings.       #
######################################################################
```

I do understand you want to have many services installed on one server but FOG isn't made for this. We recommend you to use a separate instance (be it a VM or hardware) to run FOG. Sure I understand it's not nice FOG overwrote your things but you have been warned.

> By the way, is FOG installation internet connection dependable ?

Yes. It needs to download packages from the internet. Unfortunately we don't have a full offline installer. This would need some work and we never found the time to do this.

> FOG removed by itself without warnings and asking Freeradius (which is as Dhcp as well) and atftpd.

I am not sure about Freeradius - some dependency I suppose. But Ubuntu does not allow for atftpd and tftpd-hpa to be installed side by side. So the installer just pulled in tftpd-hpa causing the removal of atftpd (not by intention though). Not nice but see, we have to keep the balance between users who have never used Linux before and want to install FOG and very advanced users like you are. As of now the scales seem to be on the newb users just because they can't help themselves. Most advanced Linux users just work around the caveats I think. Not to say that we cannot change this but it needs people who work on this project. We do a lot but the team is very small and time is scarce. I will see if there is a good way of detecting such a removal and bail out.

> And during FOG installation some other soft was removed, for example Kannel, Freeradius and other soft using libpcre libpcre3 8.41 version, reduce it to 8.39

Can you please upload the full installer debug log (found in `fogproject/bin/error_logs/fog_error_1.5.8.log`) to pastebin and post a link here? I will take a look what was causing this and see if we can prevent from this in the future.

> Also I use Php from Ondřej Surý repository.

The more modifications you make to the system the less our installer is able to do it's work without interfering.

**Comment by CpServiceSpb** [comment]
> I do understand you want to have many services installed on one server
but FOG isn't made for this. We recommend you to use a separate instance
(be > it a VM or hardware) to run FOG. Sure I understand it's not nice FOG
overwrote your things but you have been warned.

Yes, I have some important installed components on the same machine.
But as I suppose to due to either FOG is a modular system or it uses some
soft kinda module.
That is core, web UI, pxe, tftp, dhcp.
For working of web UI Web server is necessary, pxe - is ipxe (as a way) ,
as tftp - is hpa-tftp, regarding dhcp there is 1 mainly known - ISC (great
one) .
But it turns out that there is other soft not no worse then using as a FOG
part or as for FOG.
As for ipxe, I built mu own deb package of ipxe (almost latest git) with an
embedded script, and I can embed any script I want.
As for tftp - I think atftpd is not worse then hpa-tftpd.
As for Dhcp - Freeradius is powerful Dhcp as well.
And it is amazing all it work together.
That is I can boot as ISO, as WIM via ipxe/tftp/dhcp using soft mentioned
above.
But as I saw your soft is quite nice so, for these purposes.
And I don' t think that there are some difficulties to change your
installation script which is well done, which is allowed to install all
necessary components as FOG itself by "one clicking" as in Windows world.
But it would be better either add tftp/dhcp alternatives - provide a choise
during installation, which tftp/dhcp server is used for it or include
setings files only for manual installation of non default tftp/dhcp servers
or add 3-rd way to install AND set up tftp/dhcp later manually.
I may provide suggestions and config files for Freradius dhcp and atftpd.

May be make installation script more detailed (for advanced users) to give
a chance to choose components which user likes.

During instalation, FOG script changed some dependencies, in particular
libpcre3 (decreses version) , which was affected to pcre, as a following
Php, Kannel, Freradius was broken as a following Apache2 didnt' t start
also.

Зperfectly, I would like to get pxe menu from my own created items and from
FOG (on remote pxe enabled and loaded client) for example:

1. My items
    |_
      1.1 Non FOG Bla-bla-bla
      1.2 Non FOG Bla-bla-bla
2. FOG items
     |_ 2.1 FOG Bla-bla-bla
         2.2 FOG Bla-bla-bla

And I am ready take part in it with GOG developers.



ср, 29 апр. 2020 г. в 08:28, Sebastian-Roth <notifications@github.com>:

**Comment by Sebastian-Roth** [comment]
> But it turns out that there is other soft not no worse then using as a FOG part or as for FOG.

Sure I understand what you mean. I am **not** saying the only components one is able to use with FOG are hpa-tftpd, ISC-dhcp, vsftpd and nothing else will work. But so far we have not had many requests from people who want to use other components and it's major work to include that because we need to make sure this is working on Ubuntu 16.04 to 20.04, Debian 8 to 10, CentOS 6 to 8, Fedora 30 to 32, ARCH Linux... Any chance you'll help us with all that?

> During instalation, FOG script changed some dependencies, in particular libpcre3 (decreses version) , which was affected to pcre, as a following Php, Kannel, Freradius was broken as a following Apache2 didnt' t start also.

Maybe because of external repositories you were using? As I said, I would need to look through the install error logs to find out.

> I would like to get pxe menu from my own created items and from FOG (on remote pxe enabled and loaded client) for example: ...

For that we have the option to add custom iPXE entries in FOG. Go to FOG Configuration -> iPXE New Menu Entry (URL: http://fogserer/fog/management/index.php?node=about&sub=newMenu) to create new entry and FOG Configuration -> iPXE Menu Item Settings (URL: http://fogserer/fog/management/index.php?node=about&sub=customizepxe) for modifications.
