### ISSUE TITLE
Images -> Captured # not sortable

### ISSUE THREAD

**Issue by frankenzipfel** [FOGProject/fogproject#399]
https://xyz.abc/fog/management/index.php?node=image

last column "Captured" is not sortable.

Version 1.5.9-RC2.9 / FF+Chrome

**Comment by trav3711** [comment]
Where can I find the "Captured" column to try and work on this?

**Comment by frankenzipfel** [comment]
![images-captured](https://user-images.githubusercontent.com/20027810/89378219-a3b27500-d6f3-11ea-9c73-0fef170ea423.png)

**Comment by Sebastian-Roth** [comment]
@frankenzipfel Sorry for the late response. Too many other projects needing our attention at the moment. I will take a look at this soon.

What happens when you click on the column description to make it sort. Does it change the up/down arrows or nothing at all? Does sorting work for you through the other columns?

**Comment by Sebastian-Roth** [comment]
@frankenzipfel Took another while till I got to this. It should be fixed now in the latest `dev-branch` version with [commit 8095a66a](https://github.com/FOGProject/fogproject/commit/8095a66a0ba0d6b894fc15dedfc0d141955cab5b). Would be great if you could give it a try and let me know.

**Comment by frankenzipfel** [comment]
Thanks a lot, now it's sortable.... closed :)
