### ISSUE TITLE
after quick reg, host won't deploy automatically

### ISSUE THREAD

**Issue by symrex** [FOGProject/fogproject#402]
You are currently running version: 1.5.9-RC2
1. fresh installed FOG Server
2. created an image and captures it without problems
3. FOG Settings -> iPXE Menu Item Settings/iPXE Menu Customization (left menu bar has different title, then menu header itself) -> `fog.reg` -> `Default Item` [x]
4. FOG Settings -> FOG System Settings ->`FOG Quick Registration`
````
QUICKREG AUTOPOP: checked
QUICKREG IMG ID: win10
QUICKREG OS ID: No image specified (?)
QUICKREG SYS NAME: newpc-*
QUICKREG SYS NUMBER: 1
QUICKREG GROUP ASSOC: testgroup
QUICKREG IMG WHEN REG: checked
QUICKREG PROD KEY BIOS: checked
````

* When booting into PXE, pc is automatically select `Quick Reg` and perform well. (new client in host-list)
-> Problem is that this pc won't deploy automatically, he just reboot into hdd

Should i missed some logs/information please let me know.

**Comment by symrex** [comment]
Ok after a "full registration" he also does not want deploy automatically...
After successful registration, pc just reboot and boot into hdd.
Is there a command, to redirect the next boot to PXE?
Or a possibility not to reboot after registration but directly start Partclone?

I've got several rooms with pc's with old images; i would like to automate the hole process.
WOL into PXE -> Quick Reg (automatic selection) -> Deploy image with FOG Client preinstalled -> drink delicious jasmin tee

**Comment by George1422** [comment]
The short answer is to pxe boot on the next reboot, that is dependent on your firmware. I know with Dell and the CCTK you can set the flag to pxe boot on the next boot. 

With that said, I believe I helped someone before hack the quick registration script to image directly after quick image without rebooting. I don't think I turned it into a tutorial because it seemed like a one off issue. Let me see if I can find it. The solution was pretty simple to update the registration file to jump into imaging after registration.

**Comment by Sebastian-Roth** [comment]
@symrex Is there anything else we can help you with regarding this topic?
