### ISSUE TITLE
Unable to locate Image Store

### ISSUE THREAD

**Issue by danboid** [FOGProject/fogproject#412]
I installed FOG 1.5.9 under Ubuntu 20.04. I was able to capture an image fine but my first two attempts to deploy it (via multicast) failed with an error like `Unable to locate Image Store`.

The reason for this was revealed by looking at the images properties in the web UI. The Image Path option was incorrect - it was populated by the name of the image rather than the directory of the image files, also it was stashed away within /images/dev. To work around this is had to move the directory up one level out of /images/dev into /images and change the image path to the correct name of the images dir.

**Comment by Sebastian-Roth** [comment]
@danboid When an image is being captured it's stored in a directory within `/images/dev/` named by the MAC address of the host machine - e.g. `/images/dev/ef212c2a42a1/`. If the capture is being finished successfully it will be moved over to `/images/` and named after the image path/name - e.g. `/image/win10_2004_64bit/`. That's how FOG has worked ever since I know it.

So the main question is: Why didn't the capture task finish correctly in your case?

Often this happens because people use the `fogproject` to login and work on the machine - changing it's password. But this account is being setup for the inner logic of the FOG services and should not be fiddled with. But there are other causes as well. The best way to figure out why it didn't rename the folder accordingly you'd create a fresh capture task in the web UI but before you click the button there is a checkbox for making it a **debug** task. Then you startup the host to capture from as usual, wait till it boots up and hit ENTER twice to get to a terminal/console. Here you type in the command `fog` to start the process and step through it. When you get right to the end I am fairly sure you will see a warning or error saying that is wasn't able to "Update the database". Take a picture of that error on screen and post here.

**Comment by danboid** [comment]
> @danboid When an image is being captured it's stored in a directory within `/images/dev/` named by the MAC address of the host machine - e.g. `/images/dev/ef212c2a42a1/`. If the capture is being finished successfully it will be moved over to `/images/` and named after the image path/name - e.g. `/image/win10_2004_64bit/`. That's how FOG has worked ever since I know it.
> 
> So the main question is: Why didn't the capture task finish correctly in your case?

Did it not? I didn't watch FOG capture the image after it had started. I walked away and when I came back it was booted back into Windows so I just presumed it had completed succesfully and rebooted itself.


> 
> Often this happens because people use the `fogproject` to login and work on the machine - changing it's password. But this account is being setup for the inner logic of the FOG services and should not be fiddled with. But there are other causes as well. The best way to figure out why it didn't rename the folder accordingly you'd create a fresh capture task in the web UI but before you click the button there is a checkbox for making it a **debug** task. Then you startup the host to capture from as usual, wait till it boots up and hit ENTER twice to get to a terminal/console. Here you type in the command `fog` to start the process and step through it. When you get right to the end I am fairly sure you will see a warning or error saying that is wasn't able to "Update the database". Take a picture of that error on screen and post here.

I was logged in as my normal user on the FOG server and logged into fog as the default fog user.

```
Then you startup the host to capture from as usual, wait till it boots up and hit ENTER twice to get to a terminal/console. 
```

I'm not to clear on what you mean here. I thought FOG starting the imaging tool automatically after boot if assigned a task, otherwise I thought the default FOG menu option was "Boot off first hard disk".

I likely won't get to test this again until next week now unfortunately.

**Comment by Sebastian-Roth** [comment]
> I'm not to clear on what you mean here. I thought FOG started the imaging tool automatically after boot if assigned a task, otherwise I thought the default FOG menu option was "Boot off first hard disk".

Please read my post again. I said that you'd create a so called **debug** task. This way you get to a console on the machine.

**Comment by danboid** [comment]
If FOG failed during image capture, I would expect it to show an error and not reboot after a delay.

Does FOG auto-reboot (after a delay) if it fails during image capture or deployment?

**Comment by Sebastian-Roth** [comment]
@danboid said:
> Does FOG auto-reboot (after a delay) if it fails during image capture or deployment?

Yes, [it does reboot](https://github.com/FOGProject/fos/blob/master/Buildroot/board/FOG/FOS/rootfs_overlay/usr/share/fog/lib/funcs.sh#L1519) (or shutdown depending on your settings) one minute after an error occurs. It's been like this for many years, way longer than I am part of the dev team. @mastacontrola Do you remember why it was decided to do a reboot on failure instead of just waiting for someone to come along a switch it off?

**Comment by mastacontrola** [comment]
Well, normally, the reboot caused a task cycle issue. Basically it would reboot and start the capture task all over again.

In the distant past it just stayed at the failure screen indefinitely. We figured a constant indefinite amount of time is far worse than having a machine in a boot loop. At least a boot loop would be fairly recognizable.

**Comment by Sebastian-Roth** [comment]
@danboid Do you still get the "Unable to locate image store" or can we close this issue?

**Comment by danboid** [comment]
No, I didn't get this error after re-installing.
