### ISSUE TITLE
Unable to perform cloning in DELL 3620 system, able to upload / create the image

### ISSUE THREAD

**Issue by tamhankarni3** [FOGProject/fogproject#420]
Hello Experts,

I am new to FOG. I have FOG version 1.5.7 installed on Ubuntu 18.04.4 LTS.
Works fine with my other systems and able to clone the images.

I have DELL 3620 system where I am facing issues, unable to clone the image

![Error 1](https://user-images.githubusercontent.com/62698391/108326861-c10ee280-71f0-11eb-9109-dd1df6b7b996.jpeg)
![Error 2](https://user-images.githubusercontent.com/62698391/108326869-c2d8a600-71f0-11eb-815f-81377955509b.jpeg)
![Error 3](https://user-images.githubusercontent.com/62698391/108326870-c2d8a600-71f0-11eb-9055-e2363f2be3ae.jpeg)

Can someone please let me know, how to overcome the issues

Thanks & Regards,
NT

.
Attached is the error snapshot

**Comment by Sebastian-Roth** [comment]
Hello @tamhankarni3, welcome to FOG!

> I am new to FOG. I have FOG version 1.5.7 installed on Ubuntu 18.04.4 LTS.

Did you setup this FOG server or take it over from someone else? Currently FOG 1.5.9 is the latest stable release and we can't put much effort in to support older versions!

You seem to be mixing up a few things here. The pictures show image upload as well as deploy and also two different images. Very hard to know what you are doing exactly. Please tell us more about what you want to do and why different images are seen...

First picture is an image upload/capture. FOG tries to get the content of the second partition (sda2) but fails due to filesystem issues I would think. Can you still boot that machine into Windows? Run chkdsk several times to make sure the filesystem on the second partition is clean. Best if you can post the contents of the text file `d1.partitions` (should be in `/images/dev/d89ef342a236/` on your FOG server) so we know what your partition layout looks like.

No idea what could cause the this kernel panic. At what stage did you get that?

Pictue three is an image deploy to the machine. It fails because it can't properly read the image file. Please run the following two commands on your FOG server and post results here:
```
ls -al /images/DELL3620/
file /images/DELL3620/*
```

**Comment by tamhankarni3** [comment]
Hello Sebastian-Roth,

thanks for your reply.
Actually I am applying/cloning image to same hardware.

below is the snap requested by you.
![image](https://user-images.githubusercontent.com/62698391/108416309-86d72c80-7254-11eb-9f7b-b559806604ed.png)

**Comment by Sebastian-Roth** [comment]
@tamhankarni3 I did ask a few questions which I would hope you can answer.
1. Did you setup this server? Why is the old version 1.5.7 used?
2. Why do we see different image names (DELL3620 and DELL3620v1) in the pictures? Which issue should we focus on, the upload/capture (DELL3620v1) or the deploy/download (DELL3620)? If we keep mixing up things it's not going to get us anywhere. From you saying that you want to "apply/clone image to same hardware" I take we focus on that part first!
3. From the timestamps in the picture we see that DELL3620 was captured fairly recently. Did that capture without any issue? Just want to make see if we can trust this to be a valid image.

As we see the deploy failed on the very first partition (sda1) I would check the compressed image file is not corrupted. Run the following commands to see if the file extracts properly:
```
cd /tmp
cp /images/DELL3620/d1p1.img d1p1.img.gz
gunzip d1p1.img.gz
file d1p1.img
```
Post output of the commands here.

PS: The partition layout (as seen from the file sizes of d1pX.img files and the output of d1.mbr) will not properly resize to fit on different size disks because the main Windows partition is second and after that we see two more partitions that would block shrinking this to a smaller size disk as well as expanding it to a larger. Just so you be warned.

**Comment by tamhankarni3** [comment]
After upgrading the FOG to latest version I am able to Capture and Deploy image.

Thank you for your support!!!!!!!
