### ISSUE TITLE
No free mft record for $MFT: No space left on device

### ISSUE THREAD

**Issue by MikeRavenelle** [FOGProject/fogproject#421]
After my last issue with the partition not resizing I was able to "fix" the problem and capture an image.

I attempted today to capture a new image and I am getting this error. I have ran chkdsk quite a few times as well as other windows scans. No errors or issues anytime. Windows works great and has no issues booting or accessing files.

I was able to take a full image of the device with no resizing but if I want the image to be resizable this error continually happens. I ran through debug capture and took this picture when the error occurred. The device has a 64Gb NVme with only 22.2% of space used.

![mft issue](https://user-images.githubusercontent.com/7004556/115771514-a59c9100-a373-11eb-8781-cfec7358e712.jpg)

**Comment by MikeRavenelle** [comment]
I somehow once again got it to work with no explanation(at least that I understand).

I changed the compression to 4 for the image.

I then changed CAPTURERESIZEPCT to 6,10 and finally 15. It started capturing when it was set to 15.

**Comment by Sebastian-Roth** [comment]
@MikeRavenelle Sorry for the late response. Depending on the fragmentation of your data I can imagine that the default free space FOS keeps when shrinking (CAPTURERESIZEPCT) can cause an issue. We use the external tool nftsresize and there is not much we can do about it. As long as you are able to do the capture by increasing the percentage.

**Comment by dagelf** [comment]
The NVME (just like SSD's) don't do what you think it does underneath... it never clears space, it keeps its own internal index of what is written where. So it might say "sorry the disk is full" when there is a lot of free space, because it thinks the free space is still used. That is what "fstrim" or "trim" commands are for, and I suspect ntfsresize hasn't been updated to take this into account yet. Reason being, probably because few people push the limits and run into edge cases like this.
