### ISSUE TITLE
Issues while installing FOG on Fedora Server 34

### ISSUE THREAD

**Issue by rijenkii** [FOGProject/fogproject#425]
Firstly, if system was installed with "Minimal Install" selected in "Software Selection" section, `openssl` won't be installed and FOG installer will fail while trying to generate CA certificates, last two lines from the log:

```
../lib/common/functions.sh: line 1822: openssl: command not found
../lib/common/functions.sh: line 1823: openssl: command not found
```

---

Secondly, after the manual installation of `openssl`, FOG installer will still fail, but this time it will "silently" fail creating a `/etc/xinitd.d/tftp`, and then loudly fail starting `xinetd.service` because there is no `xinetd` package in repos.

Foreshadowing in the package installing stage:
```
 * Skipping package: xinetd....................................(Does not exist)
```

"Silent" fail part of stdout:
```
 * Setting up and starting TFTP and PXE Servers................../lib/common/functions.sh: line 534: /etc/xinetd.d/tftp: No such file or catalog
```

Last 4 lines of the log:
```
Failed to enable unit: Unit file xinetd.service does not exist.
Failed to stop xinetd.service: Unit xinetd.service not loaded.
Failed to start xinetd.service: Unit xinetd.service not found.
Unit xinetd.service could not be found.
```

**Comment by rijenkii** [comment]
For the record, it is possible to install `xinetd` from [Fedora 33 rpm](https://fedora.pkgs.org/33/fedora-x86_64/xinetd-2.3.15-34.fc33.x86_64.rpm.html).

**Comment by Sebastian-Roth** [comment]
@rijenkii Thanks for reporting this issue. About `openssl`: Seems like we have not noticed that because all minimal installs of the other distros still come with openssl. We might add that to the default packages list of the installer.

Now for `xinetd`... It's very hard to keep up with the changes made in all the distros we try to support. Fedora is not high on the list and so we haven't run into that yet. [Others also report](https://forums.fedoraforum.org/showthread.php?326077-No-more-xinetd-in-f34-repos&p=1847462) that `xinetd` is not available in Fedora 34. Manually installing the F33 RPM is probably your best choice. Don't think that we should try to work around this in the installer.

**Comment by Sebastian-Roth** [comment]
Whoops, didn't want to close this right away.

**Comment by Sebastian-Roth** [comment]
Dependency to `openssl` added in a141d1014 and 7e591a54f
