### ISSUE TITLE
Multicask tasks does not appear in multicast tasks list (fog 3710)

### ISSUE THREAD

**Issue by jmorda** [FOGProject/fogproject#48]
Hi, when starting a multicast task from a group for example, in the task list, all task appears but nothing appear in mmulticast tasks list. (fog 3710)

**Comment by jmorda** [comment]
Problem identified by the same problem than stuck multitask cloning : interface received by getInterface() is not the correct one.

**Comment by mastacontrola** [comment]
Multicast tasks will only show up in the task list once the UDP Cast task has started.  However, if the tasking completes (Due to interface being incorrect, or otherwise indisposed) it will remove the task as cleaned because from the Class' standpoint, the task completed properly.  All the multicast task class is looking for is tasks, and if no tasks are found, it's looking for the pid status of the udp job.  If the udp-sender command is no longer present, it will clean up the task(s) associated with that particular job and make it look like the task no longer exists, but it will not clean up the dangling host taskings.  I may look into that, but now that I know what was causing the "cleaned as complete" issue, this should be irrelevant.  Of course you do need to know to specify the proper network interface for the node that will be handling the udp-sender tasking.
