### ISSUE TITLE
[BUG] - read ERROR: No such file or directory

### ISSUE THREAD

**Issue by olahouze** [FOGProject/fogproject#485]
Hello

### BUG : 
I had a problem when deploying an image with the FOG

Error message : 
```
read ERROR: No such file or directory
Args Passed: /images/<image>/d1p2.img* /dev/<disk>
```

For me, it was a problem of user rights on the FOG

Before : 
`drwxrwxrwx. 2 root root 190 Jun 29 15:07 <image>`

After:
`drwxrwxrwx. 2 fogproject root 190 Jun 29 15:07 <image>`

I had to do a "chown" on my image folder in the **/images** directory to add the owner to **"fogproject"**

When creating a new image in the FOG GUI, the folder rights management is not well handled

Also, when "capturing" an image from a workstation, the rights revert to root:root

### Request:
Manage folder rights correctly when :
- Creating an image in the GUI
- Capturing an image from a workstation

Sincerely

**Comment by olahouze** [comment]
Hi

Could you take care of the ticket ?

best regards

**Comment by Sebastian-Roth** [comment]
@olahouze The permissions as posted above (`drwxrwxrwx.`) cannot cause the problem described because the directory was accessible (and writable) for any user (all access for anyone) - see [Linux permissions](https://linuxcommand.org/lc3_lts0090.php).

The "No such file or directory" message is kind of misleading because the d1p2.img file is being piped through a decompression command instead of being read directly. So when you see the "No such file or directory" it actually means that the decompression command died (most likely due to a corrupted file or RAM issues on the client machine) and lost it's FIFO file provided to read the piped decrompressed output.


> When creating a new image in the FOG GUI, the folder rights management is not well handled
> Also, when "capturing" an image from a workstation, the rights revert to root:root

You are right the files don't get the ownership `fogproject` when being uploaded but it's not causing a problem.
