### ISSUE TITLE
fog 3710 multicast does no start. Port problem ?

### ISSUE THREAD

**Issue by jmorda** [FOGProject/fogproject#49]
HI,

Multicast sessions does not start anymore, they are stuck on starting to restore partition partclone screen, even after --max-wait delay.

**Comment by jmorda** [comment]
Update : FOG_UDP_STARTINGPORT in fog settings change every multitask launche.... ???

**Comment by jmorda** [comment]
Found eth0 interface in udp-sender command...

**Comment by jmorda** [comment]
found ! master node setting interface was not the same as interface in fog settings for multicast but why ???

**Comment by mastacontrola** [comment]
The interface used to go through FOG_UDPCAST_INTERFACE, but ultimately it's up to the node to start and stop the multicast tasking.  This means, the interface setting in Global settings can only operate on a single node, not any master node.  In fixing the problems described in issue #45 I moved the interface to be dependent on the nodes interface setting.  Ultimately this is the interface that matters anyway.  I only know of this being a fix for multicast because I run multiple servers (yes servers) from a central database store.  My fedora box has an interface name of eno16777728 while the ubuntu box has an interface name of eth0.  Because my Fedora box is my primary, the Global setting was set to eno16777728.  But the image I was working with came off my ubuntu box.  It was attempting to start the udp cast on the eno interface which ultimately failed because that interface did NOT exist on the ubuntu box.  Hopefully this make sense, and it also makes multicast tasks much more dynamic and workable.

**Comment by jmorda** [comment]
You're a god ;-)

**Comment by heryvandoro** [comment]
this also happened to me, how to solve it?
