### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [FOGProject/fogproject#506]
Dear @FOGProject team,

There are several PRs, it is possible to have a new release build?

Thanks in advance.

Regards.

**Comment by Sebastian-Roth** [comment]
@Neustradamus There has been a discussion on this in the forums lately: https://forums.fogproject.org/topic/16507/release-of-new-fog-version

You are more than welcome to help test FOG to make it ready for a next release. This is a community driven project and it needs people to help on getting things done.

**Comment by z11k** [comment]
i see mentioned on this git dev-branch alvays. I encounter multiple issues, but consider that previosly released version:

Version 1.6.0-alpha.1161

it is named alfa but even i testing shortly it is in MUCH better state then devel, if you have elan publish new version, give it try.

**Comment by Sebastian-Roth** [comment]
@z11k said:
> i see mentioned on this git dev-branch always. I encounter multiple issues

You are more than welcome to report any issue you find with `dev-branch` on GitHub or in the forums. This is how a community driven project like FOG works. People use it, report problems and hopefully someone will find the time to fix those.

> but consider that previously released version: Version 1.6.0-alpha.1161 it is named alfa but even i testing shortly to me seems in better state then dev

It's your choice to use whatever you want. While the 1.6.0-alpha.X version (also named `working-1.6`) was in a good state roughly one and a half years ago there hasn't been much work put into this branch since then - just developers are missing. So from my perspective 1.6.0-alpha.X is fine if you want to stick with PHP 7 but not with PHP 8. And there are a few more issues I know about in 1.6.0-alpha.X but that's just my 50 cents.

> Why this version was not finalised and published? solid releas candidate.

Once again, because hardly anyone helps developing/testing/finishing/publishing FOG...

**Comment by Neustradamus** [comment]
Thanks for your reply!

It is not possible to use "master" branch for up-to-date code?

It will be better to have new improvements, new PR from community...

**Comment by Sebastian-Roth** [comment]
@Neustradamus You can send in PR on branches other than `master`. So I don't understand why it would be better?

Anyway, you are more than welcome to get involved and help improve things.

**Comment by Neustradamus** [comment]
@Sebastian-Roth: I know but continuous code in master is really better...

**Comment by wayneworkman** [comment]
@Neustradamus master is stable code. dev-branch is for code that is in-flight and perhaps not stable. You are welcome to be a tester, and report issues here or in the community forums.
