### ISSUE TITLE
Add a feature to remove data images from HDD

### ISSUE THREAD

**Issue by Neustradamus** [FOGProject/fogproject#535]
Dear @fogproject team,

When we delete an or several images from "Image Management", the image data folders on the HDD are not removed.

Can you add a feature to remove the image data folder?
For example, with a checkbox and a "Are you sure? Yes or No" window dialog box?

Thanks in advance.

PS : Do not forget all previous images already deleted from Fog user interface which are always here on the HDD.

**Comment by Quazz** [comment]
There's a "Delete files" checkbox when deleting an image. Perhaps you're using an old version?

**Comment by Neustradamus** [comment]
@Quazz: When it has been added?

**Comment by Sebastian-Roth** [comment]
@Neustradamus This has been in FOG for a very long time, maybe ever since it was released, I am not sure.

This topic has been discussed in the forums several times:
https://forums.fogproject.org/topic/13731/image-deletion-issue-if-mass-mode-used
https://forums.fogproject.org/topic/13292/images-won-t-be-deleted-in-filesystem-when-using-the-webui-delete-option
https://forums.fogproject.org/topic/14984/deleting-an-image-in-the-web-ui-is-not-removing-it-from-the-server
https://forums.fogproject.org/topic/12714/option-to-delete-files-when-deleting-multiple-images-snapins
https://forums.fogproject.org/topic/13472/pb-free-space-fog-1-5-5

> Do not forget all previous images already deleted from Fog user interface which are always here on the HDD.

I am sure we don't want to do this. Deleting data is up to the server administrator, not us!
