### ISSUE TITLE
HP Z2 tower workstations are stuck at `refind initializing` state

### ISSUE THREAD

**Issue by laurivehkaoja** [FOGProject/fogproject#537]
First, I'm not sure if this is even a FOG related bug.

I'm having problems when booting HP Z2 tower workstations to Windows over PXE. Computer's get stuck at  `refind initializing` state. I'm using the dev-branch. 

I have also found a fix for this. Renaming `refind_x64.efi` (located at `/var/www/html/fog/service/ipxe`) to something else and then renaming `refind_efi` (found at the same directory) to `refind_x64.efi` allows computers to boot normally.

**Comment by Sebastian-Roth** [comment]
@laurivehkaoja Is the mentioned HP Z2 tower workstation a pure 64 bit architecture?

When a machine PXE boots the iPXE code tries to detect the architecture to send the correct binary. So the next question arises. What happens when you schedule a deploy task? Probably pulls `bzImage` (instead of `bzImage32`), right? Any issues with the deployment?

**Comment by Sebastian-Roth** [comment]
@laurivehkaoja Anything we can help you with on this topic?

**Comment by Sebastian-Roth** [comment]
Feel free to post here if you need further help. Closing for now.
