### ISSUE TITLE
[working-1.6] Button does nothing

### ISSUE THREAD

**Issue by dmpmuniz** [FOGProject/fogproject#558]
there a error on  last option of create new host, on active directory the checkbox button does nothing.

![Captura de tela 2023-03-14 112017](https://user-images.githubusercontent.com/72808270/225031799-cd50f86e-75ff-4666-9424-7c9ded34014b.png)

 - FOG version 1.6

**Comment by darksidemilk** [comment]
May be related to #548

**Comment by mastacontrola** [comment]
Not sure I follow the issue here.

I'm able to create without issue on my side.

From the browser, can you open development tools (Chrome this is CTRL+SHIFT+C) and from the developer tools look at console tab, and attempt the add.

I'm not seeing issues creating hosts from the UI. I have not yet been able to look at #548

**Comment by darksidemilk** [comment]
@dmpmuniz Can you update to the latest working-1.6 and try again. #548 has been resolved and those changes may resolve this for you as well

**Comment by mastacontrola** [comment]
Due to length of time and my own "confidence :dagger: lol" this is indeed fixed, closing the issue.

Thank you,

**Comment by dmpmuniz** [comment]
Sorry Bro, i dont work with anymore, i Just read It now, i belive in you,
Thanks só much for te fix, have a Nice day :)

Em sex., 19 de jul. de 2024 11:36, Tom Elliott ***@***.***>
escreveu:
