### ISSUE TITLE
UDP-Cast not working for CentOS.

### ISSUE THREAD

**Issue by miszr** [FOGProject/fogproject#57]
After installing FOG on CentOS 7, I wanted to try running a multicast session when I noticed that the multicast session was unable to start.

Following the multicasting guide on the wiki i get an error when running:
```bash
sudo udp-sender --file /opt/fog/.fogsettings --log /opt/fog/log/multicast.log --portbase 13123 --ttl 1 --nopointopoint
```
Error:
```
bind socket to $ip:13124 (Address already in use)
```

My first reaction was that it must be a program that uses that port for something, but after using `netstat`, `lsof` and `fuser` i was unable to find a program that was using that port.

So this problem seems to be related to that I am running CentOS on the server, because I have tested multicasting from a Ubuntu install earlier last week and was able to run it correctly.

After reading the UDP-Cast code I noticed that it was not using the `SO_REUSEADDR` option on the primary socket. After adding that option and recompiling it worked flawlessly.

Here is a patch of the changes I made to get UDP-Cast working under CentOS:
```patch
--- udpcast-20120424/console.c  2011-07-10 09:48:02.000000000 +0200
+++ udpcast-20150811/console.c  2015-08-11 19:44:30.431414882 +0200
@@ -3,6 +3,7 @@
 #include <stdio.h>
 #include <errno.h>
 #include <string.h>
+#include <sys/select.h>

 #include "console.h"
 #include "util.h"
@@ -11,7 +12,6 @@
 #ifndef __MINGW32__

 #include <termios.h>
-#include <sys/select.h>

 struct console_t {
     int fd; /* Filedescriptor for console, or -1 if disabled */
--- udpcast-20120424/socklib.c  2011-07-10 09:40:37.000000000 +0200
+++ udpcast-20150811/socklib.c  2015-08-11 19:30:54.806886067 +0200
@@ -934,6 +934,13 @@ int makeSocket(addr_type_t addr_type,
       closesocket(s);
       return -1;
     }
+
+    int yes = 1;
+    if ( setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(int)) == -1 )
+    {
+       udpc_fatal(1, "setsockopt failed on socket with error (%s)\n", strerror(errno));
+    }
+
     ret = bind(s, (struct sockaddr *) &myaddr, sizeof(myaddr));
     if (ret < 0) {
        char buffer[16];
```

**Comment by mastacontrola** [comment]
I'm not 100% sure that this is the problem.  I've been testing multicast tasks on centos 7 and 6, fedora 22, 21, 20, 19, and ubuntu 15, 14, 13, 12 and not had any major issues.

I have seen cases where the interface being called is not correct for the udp session, it initiates as expected, but as udpcast simply isn't capable of starting on that particular interface (for whatever reason like it doesn't exist, or is not active, etc...) the udp-sender command immediately exits.  The task manager sees the task is not running, but was not cancelled by user interference.

I also say this because udp-cast is a third party.  Editing the file for ourselves in such a manner does not allow other groups to do things.

**Comment by mastacontrola** [comment]
Barring any issues, I'm still not seeing any problems that would require us to perform such a coding set of instructions for now.

I'm just going to close it, but please feel free to comment, and reopen as necessary to give us more information.
