### ISSUE TITLE
Debian : Auto-Upgrading PHP8.3 - Increment on type bool has no effect, this will change in the next major version of PHP

### ISSUE THREAD

**Issue by Gauthier-L** [FOGProject/fogproject#582]
Hi all !

Just for your information. Debian upgrade PHP-FPM to the newest version 8.3. The syslog return this warning : 
`PHP Warning:  Increment on type bool has no effect, this will change in the next major version of PHP in /var/www/html/fog/lib/fog/fogbase.class.php on line 974`

Best regards

**Comment by Gauthier-L** [comment]
I publish my edit for this : 

Original on line 974 : 
```
    protected function isLoaded($key)
    {
        $key = $this->key($key);
        $result = isset($this->isLoaded[$key]) ? $this->isLoaded[$key] : 0;
        $this->isLoaded[$key] = true;
        ++$this->isLoaded[$key];

        return $result ? $result : false;
    }
```

I've replace by this : 
```
        protected function isLoaded($key)
        {
            $key = $this->key($key);

            if (!isset($this->isLoaded[$key])) {
                $this->isLoaded[$key] = 1; // Initialiser à 1 s'il n'est pas défini
            } else {
                ++$this->isLoaded[$key]; // Incrémenter si déjà défini
            }

            return $this->isLoaded[$key] > 1; // Retourner true si déjà chargé au moins une fois
        }
```

All it's okey for me. You can try in dev branch.

Best regards

**Comment by ghost** [comment]
> Hi all !
>


                    Beendet

**Comment by maxcarpone** [comment]
Hey,

Thanks @Gauthier-L, it helps us clearing these messages which made our server running out of disk space.

**Comment by darksidemilk** [comment]
Apologies, I didn't see this issue till just now. 
@mastacontrola  pushed a change in this commit back in August https://github.com/FOGProject/fogproject/commit/900ccebdd2e283eff7cf19d5347d28b2d376fb7b

This got rid of the `++` on the boolean and should resolve the issue. Nothing wrong with your fix, just didn't see it before it was fixed elsewhere.

But this should be fixed in the latest stable release https://github.com/FOGProject/fogproject/releases/tag/1.5.10.1615 
Let us know if that is not the case @Gauthier-L  @SaarGirl  @maxcarpone and we'll reopen the issue.
