### ISSUE TITLE
packages/web/mainversion.php requires updating now for stable check

### ISSUE THREAD

**Issue by user-629782** [FOGProject/fogproject#607]
After upgrading over the weekend to the new "stable" branch (git checkout stable from dev-branch) and check the FoG version information (wrench in GUI) I noticed that my version was still set to dev-branch and not stable. Looking at the mainversion.php file looks like the stablecheck variable is not being set; only the dev-check var is. I believe this is a result of the switch over to the stable branch and the check logic has not caught up yet.

FoG Version: 1.5.10.48 (stable but says dev-branch)
FoG Server: Rocky Linux 9.x (latest)

I also tried a fresh install of FoG "stale" branch (seeing the warning about going back to stable/master from dev-branch) but saw the same version information. I know this is not a big problem but just thought the devs should know. Congrats on the "stable" version and the idea of folding the dev-branch into it for more relevant releases. Good job!

P.S. Shouldn't the Stable version now be 1.5.10.48 and not 1.5.10 to mimic the "stable" release?

**Comment by darksidemilk** [comment]
Thanks for bringing this to our attention and for giving the stable branch a go!
We'll get this fixed, we're for sure still working out a couple kinks as we create the new stable release flow, eventually we'll have it all automated.

We also should update that 'disclaimer' about switching between versions. Going between dev-branch and stable branch should be without issue.
Switching from the beta/working 1.6 version to the stable/dev branches or back to the master branch (which you shouldn't do now) can have issues with schema updates, but it's actually easily resolved at the moment. But we want the disclaimer because if you're jumping between db schemas you should be aware you're doing that and there's potential for unknowns.

And yes the stable branch should be 1.5.10.48 in the version view.

**Comment by mastacontrola** [comment]
Should be fixed. Thanks for letting us know.

**Comment by darksidemilk** [comment]
Full fixed in new stable version 1.5.10.1565

![image](https://github.com/user-attachments/assets/bad86e65-bfdc-46d4-a41d-b7e13f15f0a0)

![image](https://github.com/user-attachments/assets/3d77d394-0a52-4ceb-9dfa-bd1e811cdfc4)

This office website page for downloading the latest version is now updated dynamically too https://fogproject.org/download.php thanks to @mastacontrola.

Also just want to link this over to #601 as it relates to the new automated release system.

Thank you again for reporting this! @user-629782

**Comment by user-629782** [comment]
Will try this over the weekend server maintenance window. Thank you both @darksidemilk and @mastacontrola for your fast response to this.
