### ISSUE TITLE
Infiniband Mac Address - Mac format invalid

### ISSUE THREAD

**Issue by kargh** [FOGProject/fogproject#64]
Does FOG not work with 20 byte mac addresses? I couldn't find any information on The Google.

**Comment by mastacontrola** [comment]
FOG Does not, currently, support 20 byte mac addresses.  I think it's because trying to commonize the values is much simpler using the typical 12 (no dash,space, or colon) hex digit setup.  Seeing as pretty much everything else is true, if you know of a regex that if it's 12 or equal to 20bytes, maybe that'd work for the needs?

I'm just thinking here, and it may not even be possible to accurately determine infiniband mac address.
