### ISSUE TITLE
Fog Master server with NAT (dev-branch)

### ISSUE THREAD

**Issue by hregis** [FOGProject/fogproject#83]
Hello

My Fog master server is in my local network with a private IP address. I set Fog with the public IP address of my internet connection and does a NAT. I have a Fog storage node outside my local network with a public IP. Everything works fine except replication. I have this error message: "This is not the master node".
in fact comparing the server private IP address and public IP address of Fog in database does not match. of course! :-)
to correct the problem I changed the line 18 of the file "/var/www/fog/lib/service/fogservice.class.php" :

`exec("/sbin/ip addr | awk -F'[ /]+' '/global/ {print $3}'",$IPs,$retVal);`

replace by

`exec("/usr/bin/dig dig +short myip.opendns.com @resolver1.opendns.com",$IPs,$retVal);`

This gets the public IP address of my internet connection.

You can add an option to set this in future versions?

Thank you

**Comment by mastacontrola** [comment]
We already resolve hostnames.  My guess, it's unable to resolve it as your network is filtering lan/wan redirects (it can't access the public facing IP side).

Adding the dig is doable, except it's not a guarantee the package is installed on all OS's

**Comment by hregis** [comment]
if i use hostname of my public ip address or my public ip directly (Image Replicator logs) :

> | This is not the master node

**Comment by mastacontrola** [comment]
What if you add your FQDN to the /etc/hosts file, pointing at the appropriate public facing IP address?

**Comment by hregis** [comment]
it's not a DNS problem !

getIPAddress() return my private ip and checkIfNodeMaster() compared this private ip with master storage in database :

($this->getClass('StorageNodeManager')->find(array('isMaster'=>1,'isEnabled'=>1))

and my master storage is configured with a public ip for external client !

you see ?

**Comment by mastacontrola** [comment]
I'm not saying it's a DNS problem.

If the host has the FQDN in the /etc/hosts file with the appropriate public facing IP address, it should return all matches.

You can even validate this by changing the IP field to be that of the FQDN of the node.

**Comment by hregis** [comment]
same problem :

> [02-19-16 8:05:20 pm] * | This is not the master node

**Comment by hregis** [comment]
dig and curl is install by default with fog installer ?

it's possible to use this also :

exec("/usr/bin/curl ifconfig.me",$IPs,$retVal);

and if given the opportunity to define a setting in the database in order to use its own search ip address in the function "getIPAddress()" ?

exec(trim($this->getSetting('MY_OWN_CHECK_IP'),$IPs,$retVal);

**Comment by hregis** [comment]
it's ok with the FQDN with private IP in /etc/hosts (not public)
and the FQDN in storage ip fields.

but it's not user friendly ;-)

**Comment by mastacontrola** [comment]
If it's okay with FQDN with private IP, what about creating an entry for the Private->FQDN in your dns server?

While I understand it's not "user friendly", the method of using /etc/hosts on all nodes/servers will be the fastest method to ensure the master nodes actually see themselves as the master.

That said, the FQDN based on the public facing in /etc/hosts should work unless your network is not allowing LAN/WAN redirection.

LAN/WAN redirection typically is filtered, for what I don't know.  I think it's more to stop having internet network try to communicate to public network side to come right back into the main network.

This basically means, internally (where you are, if the hostname and the network are in the same scope) any request to the FQDN will be blocked.  So if FQDN is host1.fogserver.com and public IP is 1.1.1.1, and internal network is 10.10.10.0, The request for host1.fogserver.com will look (and find usually) the 1.1.1.1, but it cannot return to the main source.  Seeing as this particular machine IS the one requesting itself, it would seem to be a bit rough to simply expect it to find and know of itself.

I do install curl on the systems, and would more prefer to use a PHP native mechanism just because I think it'd allow for more dynamic information.  That said, the ifconfig.me would work, but how?  Meaning, all Server's and Nodes MUST have internet access?  We have people who do use isolated networks.

**Comment by mastacontrola** [comment]
Now I say all that so you understand the viewpoint, but I have ALSO added the code to do what you're requesting within the GUI as well.

I've tested it, and one of the things I added was a test to verify that the server can actually reach the internet.  If it can't, it will likely print the same * | This is not the master node* message of which you will likely need to update the node anyway.

**Comment by hregis** [comment]
thank you for your help and your work @mastacontrola
