### ISSUE TITLE
Separate the services so we can run fog server in docker using docker-compose

### ISSUE THREAD

**Issue by vipconsult** [FOGProject/fogproject#98]
This is a major undertaking , but I have enough experience with docker and can work together to get this done if interested.

I managed to make it run in a container , but not the docker way (each service in a separate container) , but all services inside the same container

let me know what you think.

**Comment by Nekroze** [comment]
I would love this as I would not need to keep around a CentOS 6 box just to run fog!

This helps as I am moving all my servers to [Nixos](https://nixos.org) for better control of the system and a simple declarative configuration file to define the entire OS as what I need and nothing more.

**Comment by mastacontrola** [comment]
I have no idea what/how to do this.  Any work towards this is of course more than welcome.  Don't think my failure to communicate faster means anything either, sometimes I just can't respond :+1:

**Comment by Nekroze** [comment]
Basically we just need to write Dockerfiles that contain and run no more or less than the individual FOG service that specific container handles. So for example one Dockerfile just for the replication controller, another for the multicast service.

The only problem I can guess may occur is, what if you do not run a replication controller service/container. Can FOG handle missing one or some services? That is the benefit of splitting applications into separate services each in different containers, having optional services or ones that we can run multiple instances of seamlessly. If FOG will not yet work this way with each service on a different host (a docker container) then we might be better off working on that rather than just trying to write Dockerfiles.

**Comment by mastacontrola** [comment]
Have you guys seen this?

https://github.com/frodus/docker-fogproject

**Comment by mastacontrola** [comment]
Alright so there's no information quite yet, just a readme file, but maybe you can see if that user has made any progress?

**Comment by vipconsult** [comment]
I have already managed to run the fog server inside docker , but the problem is that the whole design is tightly coupled between the individual services so it would require few month to rewrite all bootstrap scripts to separate all service.

I want to do this but maybe in few months time when I complete few current projects.
