### ISSUE TITLE
Execute fsck before capture image

### ISSUE THREAD

**Issue by danilopinotti** [FOGProject/fogproject#99]
Today i try to capture image end appears following message:
extfsclone.c: bitmap free count err, free

Looking for this on the internet I found that running fsck in Linux partition, the problem is solved. Saw also that in Clonezilla exists -fsck-src-part parameter that is run the command immediately before capturing the image.
May have this in partclone.

Follow the link:
http://rm-rf.es/clonezilla-extfsclone-c-bitmap-free-count-err-free/

**Comment by mastacontrola** [comment]
I have no idea what you're referring to.

**Comment by danilopinotti** [comment]
I was trying to capture the image of two dual boot system with Linux and Windows. One of them gave everything right from start to finish. The other could not capture and appeared the message: Failed to complete upload (savePartition).
The second time I try and I saw that before this message appears, appeared a message on partclone saying extfsclone.c: bitmap free count err.
Searching on the internet I found that should use fsck command on Linux and chkdsk on windows to give no more problems like that, and really worked. My suggestion is you do, somehow it be automatic. In Clonezilla there is -fsck-src-part parameter, since the partclone I do not know if there is.

**Comment by mastacontrola** [comment]
FOG already does run an fsck before shrinking and after expanding as required for resize2fs.  Is this not working?

**Comment by danilopinotti** [comment]
Last time I was capture an image, I had to run the fsck manually

**Comment by mastacontrola** [comment]
Was the fsck needed on resizable or non-resizable image?  This is important.  Non-resizable means you have prepared the system specifically.  My performing checks isn't hard, but is it really required?  The "master", in the case of non-resizable, should already be set and ready to go.  Resizable has to take into account of things because you are adjusting partition layouts, for non-resize we should be able to pull/push and go.  There should not be a need to run a check on the filesystem at all.
